functional: #Правильно ли все работает с точки зрения функционала приложения/сайта
  – Пользователь должен иметь возможность зарегистрировать новый аккаунт
  - Пользователь должен иметь возможность войти на существующий аккаунт
  - Пользователь должен иметь возможность попробовать пройти баттл без авторизации
  - Авторизованный пользователь должен иметь возможность писать комментарии в чат 
  - Авторизованный пользователь должен иметь возможность создавать новую игру

non-functional: #Проверка удобства, скорости и безопасности использования приложения/сайта
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен иметь мобильную версию 
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров

implicit: #Требования к приложению, которые не обозначены в задачах, но упрощают и ускоряют процесс использования приложения/сайта
  - Пользователь должен иметь возможность переключать язык сайта на русский
  - Пользователь должен иметь возможность «добавлять в друзья» других авторизованных пользователей
  - Пользователь должен иметь возможность выставить «уровень владения своим оружием»
  
